DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS pegawais;


CREATE TABLE users (
id INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
username VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL);

CREATE TABLE pegawais (
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
nama VARCHAR(255) NOT NULL,
nip INT NOT NULL,
tgl_lahir DATE NOT NULL,
email VARCHAR(255) NOT NULL,
keterangan TEXT NOT NULL);

INSERT INTO users (username, password) VALUES ('admin', '$2y$10$5Z65fOBpNbgPR7d.KaZ5eOxAxHr.8cRT8OthqAiZKMuH3CryrHYL6');
